# golangci-lint configuration for will-it-compile
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  skip-dirs:
    - vendor
    - third_party
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
  modules-download-mode: readonly
  go: '1.24'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple)
    - unused        # Find unused code

    # Security linters (critical for this project)
    - gosec         # Security checker
    - bodyclose     # Check HTTP response bodies are closed

    # Error handling (important per CLAUDE.md guidelines)
    - errorlint     # Find error handling issues
    # wrapcheck disabled - too strict for internal packages, errors are wrapped at API boundaries

    # Code quality
    - gocyclo       # Cyclomatic complexity
    - misspell      # Fix common spelling mistakes
    - unconvert     # Remove unnecessary conversions
    - prealloc      # Find slice declarations that could be preallocated

    # Style and best practices
    - nolintlint    # Ensure nolint directives are properly formatted
    - whitespace    # Detect leading/trailing whitespace

    # Bugs and complexity
    - dupl          # Code clone detection
    - nakedret      # Finds naked returns in long functions

    # Disabled - too verbose/opinionated:
    # - revive: package comments and naming suggestions too verbose for internal code
    # - gocritic: too opinionated
    # - godot: comment punctuation is overly pedantic
    # - goprintffuncname: printf naming is stylistic preference

    # Context handling (important for timeout/cancellation)
    - contextcheck  # Check context.Context is passed correctly
    - noctx         # Finds http requests without context.Context

    # Performance
    - goconst       # Find repeated strings that could be constants
    - perfsprint    # Check that fmt.Sprintf can be replaced with faster alternatives

    # Additional production-ready checks
    - nilnil        # Check for simultaneous return of nil error and nil value
    - thelper       # Detect test helpers without t.Helper()
    - bidichk       # Check for dangerous unicode sequences
    - copyloopvar   # Check for pointers to loop variables (replaces exportloopref)
    - makezero      # Find slice declarations with non-zero initial length
    - err113        # Check errors handling expressions
    - errname       # Check error naming conventions
    - mirror        # Reports wrong mirror patterns of bytes/strings usage

    # Disabled - too strict/verbose:
    # - funlen: function length is subjective, forces unnecessary splitting
    # - gocognit: cognitive complexity similar to funlen
    # - nestif: nested if depth is subjective
    # - exhaustive: forces verbose default cases in switches

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*github.com/labstack/echo/v4.Context).JSON
      - (*github.com/labstack/echo/v4.Context).String

  gosec:
    # Security is critical - check everything
    severity: medium
    confidence: medium
    excludes:
      # G104: audit errors not checked (covered by errcheck)
      - G104
    config:
      # Docker socket usage is intentional and documented
      G204: "200" # Subprocess launched with variable - we sanitize inputs
      G304: "200" # File path provided as taint input - controlled in tests

  errorlint:
    # Check error wrapping and comparison
    errorf: true
    asserts: true
    comparison: true

  wrapcheck:
    # Encourage error wrapping per CLAUDE.md guidelines
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
    ignorePackageGlobs:
      - github.com/stretchr/testify/*

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - ifElseChain
      - whyNoLint
      - unnamedResult

  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - (github.com/labstack/echo/v4.Context).JSON
          - (github.com/labstack/echo/v4.Context).String
      shadow:
        strict: true

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  misspell:
    locale: US

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  dupl:
    threshold: 100

  nakedret:
    # Disallow naked returns in functions longer than 5 lines
    max-func-lines: 5

  contextcheck:
    # Check for non-inherited context usage
    check-func-literal: true

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocyclo:
    # Cyclomatic complexity - reasonable limit
    min-complexity: 15

  nilnil:
    # Disallow simultaneous return of nil error and nil value
    checked-types:
      - ptr
      - func
      - iface
      - map
      - chan

  thelper:
    test:
      first: true
      name: true
      begin: true
    benchmark:
      first: true
      name: true
      begin: true

  err113:
    # Check for error wrapping - only report truly dynamic errors
    report-type-errors: false

  errname:
    # Check that sentinel errors are named correctly
    check-type-name: true
    check-var-name: true

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    # Tests can have higher complexity and duplication for clarity
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - goconst

    # Exclude test mock implementations from unused checks
    - path: internal/docker/mock_test.go
      linters:
        - unused
        - nilnil

    # Allow response body close without error check (standard practice for HTTP clients)
    - source: "defer resp\\.Body\\.Close\\(\\)"
      linters:
        - errcheck

    # Unused styles in TUI are OK (may be used later)
    - path: cmd/tui/ui/styles\.go
      linters:
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false

  # Exclude known issues or false positives
  exclude:
    # EXC0001: errcheck: Almost all programs ignore errors on these functions
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked

    # EXC0005: staticcheck: Developers tend to write in C-style with explicit 'break'
    - ineffective break statement. Did you mean to break out of the outer loop

  exclude-use-default: false
